#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Run ESLint and TypeScript checks on staged files
npx eslint --fix .
npx tsc --noEmit

# Check if ESLint or TypeScript failed
if [ $? -ne 0 ]; then
  echo "Linting or TypeScript check failed. Commit aborted."
  exit 1
fi