#!/usr/bin/env sh
. "$(dirname "\$0")/_/husky.sh"

set -e

# Run ESLint and TypeScript checks on staged files
npx eslint --fix $(git diff --cached --name-only --diff-filter=ACM | grep '\.js$\|\.ts$\|\.vue$')
npx tsc --noEmit

echo "Linting and TypeScript checks passed. Proceeding with commit."
